package com.github.alexthe666.archipelago.core;

import net.minecraft.block.Block;
import net.minecraft.world.biome.BiomeGenBase;

import com.github.alexthe666.archipelago.block.BlockGlowingCoral;
import com.github.alexthe666.archipelago.block.BlockGrowingSeaweed;
import com.github.alexthe666.archipelago.block.BlockShortCoral;
import com.github.alexthe666.archipelago.block.BlockShortPlant;
import com.github.alexthe666.archipelago.block.BlockTallPlant;

public class ModBlocks {

	public static Block anthurium_andraeanum;
	public static Block bottle_palm;
	public static Block ceratozamia_mexicana;
	public static Block jambu;
	public static Block canary_island_foxglove;
	public static Block la_palma_sow_thistle;
	public static Block parrot_lily;
	
	public static Block dendrophyllia_cribosa;
	public static Block ivory_bush_coral;
	public static Block maasella_edwardsii;
	public static Block yellow_gorgonian;
	public static Block yellow_tube_sponge;
	public static Block isidella;
	public static Block bipinnate_sea_plume;
	public static Block asian_green_mussels;
	public static Block blue_mussels;
	public static Block nori;
	public static Block cerianthus_lloydi;
	public static Block common_piddock_colony;
	public static Block bladderwrack;
	public static Block caulerpa_prolifera;
	public static Block cuvie;
	public static Block green_fleece;
	public static Block spiral_wrack;
	public static Block tooth_wrack;
	public static Block caulerpa_taxifolia;
	public static Block venus_fan;
	public static Block cauliflower_soft;
	public static Block gracilaria;
	public static Block pachycerianthus_fimbriatus;
	public static Block stove_pipe_sponge;
	public static Block heteractis_magnifica_blue;
	public static Block heteractis_magnifica_pink;
	public static Block heteractis_magnifica_red;
	public static Block heteractis_magnifica_yellow;
	public static Block bubble_tip;
	public static Block acropora_nasuta;
	public static Block alveopora_spongiosa;
	public static Block acropora_samoensis;
	public static Block dendronephthya_hemprichi;
	public static Block dragon_eye_zoanthid_green;
	public static Block dragon_eye_zoanthid_red;
	public static Block favites_pentagona;
	public static Block galaxy_coral;
	public static Block leptopsammia_pruvoti;
	public static Block lobophyllia_hemprichii;
	public static Block nephthyigorgia;
	public static Block smooth_flower_coral_green;
	public static Block smooth_flower_coral_orange;
	public static Block spiral_wire_coral;
	public static Block whip_fan_orange;
	public static Block whip_fan_red;
	public static Block bennetts_feather_star;
	public static Block passion_flower_feather_star;
	public static Block xestospongia_testudinaria;
	public static Block colonial_tube_sponge;
	public static Block wakame;
	public static Block snakelocks;
	public static Block bull_kelp;
	public static Block giant_kelp;
	public static Block sea_belt_kelp;

	public static void init(){
		anthurium_andraeanum = new BlockShortPlant("anthurium_andraeanum", 5, new BiomeGenBase[]{ModWorld.tropicJungle, ModWorld.tropicShrublands});
		bottle_palm = new BlockTallPlant("bottle_palm", 5, new BiomeGenBase[]{ModWorld.tropicJungle});
		ceratozamia_mexicana = new BlockTallPlant("ceratozamia_mexicana", 5, new BiomeGenBase[]{ModWorld.tropicJungle, ModWorld.tropicShrublands});
		jambu = new BlockShortPlant("jambu", 5, new BiomeGenBase[]{ModWorld.tropicJungle});
		canary_island_foxglove = new BlockTallPlant("canary_island_foxglove", 5, new BiomeGenBase[]{ModWorld.tropicShrublands});
		la_palma_sow_thistle =new BlockTallPlant("la_palma_sow_thistle", 5, new BiomeGenBase[]{ModWorld.dryScrubland, ModWorld.tropicShrublands});
		parrot_lily = new BlockShortPlant("parrot_lily", 5, new BiomeGenBase[]{ModWorld.tropicGrasslands, ModWorld.tropicJungle, ModWorld.tropicShrublands});
		
		dendrophyllia_cribosa = new BlockShortCoral("dendrophyllia_cribosa", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicBlueHoles, ModWorld.tropicKelpForest, ModWorld.tropicTrench});
		ivory_bush_coral = new BlockShortCoral("ivory_bush_coral", 5, new BiomeGenBase[]{ModWorld.tropicOcean});
		maasella_edwardsii = new BlockShortCoral("maasella_edwardsii", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicBlueHoles, ModWorld.tropicKelpForest});
		yellow_gorgonian = new BlockShortCoral("yellow_gorgonian", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		yellow_tube_sponge = new BlockShortCoral("yellow_tube_sponge", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		isidella = new BlockGlowingCoral("isidella", 5, new BiomeGenBase[]{ModWorld.tropicTrench});
		bipinnate_sea_plume = new BlockShortCoral("bipinnate_sea_plume", 5, new BiomeGenBase[]{ModWorld.tropicReef, ModWorld.tropicBlueHoles});
		asian_green_mussels = new BlockShortCoral("asian_green_mussels", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		blue_mussels = new BlockShortCoral("blue_mussels", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		nori = new BlockShortCoral("nori", 5, new BiomeGenBase[]{ModWorld.tropicOcean});
		cerianthus_lloydi = new BlockShortCoral("cerianthus_lloydi", 5, new BiomeGenBase[]{ModWorld.tropicOcean});
		common_piddock_colony = new BlockGlowingCoral("common_piddock_colony", 5, new BiomeGenBase[]{ModWorld.tropicOcean});
		bladderwrack = new BlockShortCoral("bladderwrack", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		caulerpa_prolifera = new BlockShortCoral("caulerpa_prolifera", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		cuvie = new BlockShortCoral("cuvie", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		green_fleece = new BlockShortCoral("green_fleece", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		spiral_wrack = new BlockShortCoral("spiral_wrack", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		tooth_wrack = new BlockShortCoral("tooth_wrack", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		caulerpa_taxifolia = new BlockShortCoral("caulerpa_taxifolia", 5, new BiomeGenBase[]{ModWorld.tropicOcean, ModWorld.tropicKelpForest});
		venus_fan = new BlockShortCoral("venus_fan", 5, new BiomeGenBase[]{ModWorld.tropicBlueHoles});
		cauliflower_soft = new BlockShortCoral("cauliflower_soft", 5, new BiomeGenBase[]{ModWorld.tropicReef, ModWorld.tropicBlueHoles});
		gracilaria = new BlockShortCoral("gracilaria", 5, new BiomeGenBase[]{ModWorld.tropicBlueHoles});
		pachycerianthus_fimbriatus = new BlockShortCoral("pachycerianthus_fimbriatus", 5, new BiomeGenBase[]{ModWorld.tropicBlueHoles});
		stove_pipe_sponge = new BlockShortCoral("stove_pipe_sponge", 5, new BiomeGenBase[]{ModWorld.tropicReef, ModWorld.tropicBlueHoles});
		heteractis_magnifica_blue = new BlockShortCoral("heteractis_magnifica_blue", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		heteractis_magnifica_pink = new BlockShortCoral("heteractis_magnifica_pink", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		heteractis_magnifica_red = new BlockShortCoral("heteractis_magnifica_red", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		heteractis_magnifica_yellow = new BlockShortCoral("heteractis_magnifica_yellow", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		bubble_tip = new BlockShortCoral("bubble_tip", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		acropora_nasuta = new BlockShortCoral("acropora_nasuta", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		alveopora_spongiosa = new BlockShortCoral("alveopora_spongiosa", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		acropora_samoensis = new BlockShortCoral("acropora_samoensis", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		dendronephthya_hemprichi = new BlockShortCoral("dendronephthya_hemprichi", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		dragon_eye_zoanthid_green = new BlockShortCoral("dragon_eye_zoanthid_green", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		dragon_eye_zoanthid_red = new BlockShortCoral("dragon_eye_zoanthid_red", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		favites_pentagona = new BlockShortCoral("favites_pentagona", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		galaxy_coral = new BlockShortCoral("galaxy_coral", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		leptopsammia_pruvoti = new BlockShortCoral("leptopsammia_pruvoti", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		lobophyllia_hemprichii = new BlockShortCoral("lobophyllia_hemprichii", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		nephthyigorgia = new BlockShortCoral("nephthyigorgia", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		smooth_flower_coral_green = new BlockShortCoral("smooth_flower_coral_green", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		smooth_flower_coral_orange = new BlockShortCoral("smooth_flower_coral_orange", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		spiral_wire_coral = new BlockShortCoral("spiral_wire_coral", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		whip_fan_orange = new BlockShortCoral("whip_fan_orange", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		whip_fan_red = new BlockShortCoral("whip_fan_red", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		bennetts_feather_star = new BlockShortCoral("bennetts_feather_star", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		passion_flower_feather_star = new BlockShortCoral("passion_flower_feather_star", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		xestospongia_testudinaria = new BlockShortCoral("xestospongia_testudinaria", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		colonial_tube_sponge = new BlockShortCoral("colonial_tube_sponge", 5, new BiomeGenBase[]{ModWorld.tropicReef});
		wakame = new BlockShortCoral("wakame", 5, new BiomeGenBase[]{ModWorld.tropicKelpForest});
		snakelocks = new BlockShortCoral("snakelocks", 5, new BiomeGenBase[]{ModWorld.tropicKelpForest});
		bull_kelp = new BlockGrowingSeaweed("bull_kelp", 5, 3, new BiomeGenBase[]{ModWorld.tropicKelpForest});
		giant_kelp = new BlockGrowingSeaweed("giant_kelp", 5, 3, new BiomeGenBase[]{ModWorld.tropicKelpForest});
		sea_belt_kelp = new BlockGrowingSeaweed("sea_belt_kelp", 5, 3, new BiomeGenBase[]{ModWorld.tropicKelpForest});
	}
}
