package com.github.alexthe666.archipelago.client.model.entity;

import net.ilexiconn.llibrary.client.model.ModelAnimator;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelBase;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelRenderer;
import net.minecraft.entity.Entity;

/**
 * Created by Codyr on 05/02/2017.
 */
public class ModelKraken extends AdvancedModelBase {

        public AdvancedModelRenderer Body;
        public AdvancedModelRenderer FirstArm1;
        public AdvancedModelRenderer ThirdArm1;
        public AdvancedModelRenderer FourthArm1;
        public AdvancedModelRenderer FifthArm1;
        public AdvancedModelRenderer SixthArm1;
        public AdvancedModelRenderer SeventhArm1;
        public AdvancedModelRenderer EighthArm1;
        public AdvancedModelRenderer SecondArm1;
        public AdvancedModelRenderer Head2;
        public AdvancedModelRenderer Head1;
        public AdvancedModelRenderer Head3;
        public AdvancedModelRenderer RightEye;
        public AdvancedModelRenderer LeftEye;
        public AdvancedModelRenderer Head4;
        public AdvancedModelRenderer Head5;
        public AdvancedModelRenderer RightHorn;
        public AdvancedModelRenderer LeftHorn;
        public AdvancedModelRenderer FirstArm2;
        public AdvancedModelRenderer FirstArm3;
        public AdvancedModelRenderer FirstArmDetail1;
        public AdvancedModelRenderer FirstArmDetail2;
        public AdvancedModelRenderer FirstArmDetail3;
        public AdvancedModelRenderer ThirdArm2;
        public AdvancedModelRenderer ThirdArm3;
        public AdvancedModelRenderer ThirdArmDetail1;
        public AdvancedModelRenderer ThirdArmDetail2;
        public AdvancedModelRenderer ThirdArmDetail3;
        public AdvancedModelRenderer FourthArm2;
        public AdvancedModelRenderer FourthArm3;
        public AdvancedModelRenderer FourthArmDetail1;
        public AdvancedModelRenderer FourthArmDetail2;
        public AdvancedModelRenderer FourthArmDetail3;
        public AdvancedModelRenderer FifthArm2;
        public AdvancedModelRenderer FifthArm3;
        public AdvancedModelRenderer FifthArmDetail1;
        public AdvancedModelRenderer FifthArmDetail2;
        public AdvancedModelRenderer FifthArmDetail3;
        public AdvancedModelRenderer SixthArm2;
        public AdvancedModelRenderer SixthArm3;
        public AdvancedModelRenderer SixthArmDetail2;
        public AdvancedModelRenderer SixthArmDetail1;
        public AdvancedModelRenderer SixthArmDetail3;
        public AdvancedModelRenderer SeventhArm2;
        public AdvancedModelRenderer SeventhArm3;
        public AdvancedModelRenderer SeventhArmDetail1;
        public AdvancedModelRenderer SeventhArmDetail2;
        public AdvancedModelRenderer SeventhArmDetail3;
        public AdvancedModelRenderer EighthArm2;
        public AdvancedModelRenderer EighthArm3;
        public AdvancedModelRenderer EighthArmDetail1;
        public AdvancedModelRenderer EighthArmDetail2;
        public AdvancedModelRenderer EighthArmDetail3;
        public AdvancedModelRenderer SecondArm2;
        public AdvancedModelRenderer SecondArm3;
        public AdvancedModelRenderer SecondArmDetail1;
        public AdvancedModelRenderer SecondArmDetail2;
        public AdvancedModelRenderer SecondArmDetail3;
        private ModelAnimator animator;

        public ModelKraken() {
            this.textureWidth = 128;
            this.textureHeight = 64;
            this.Head4 = new AdvancedModelRenderer(this, 0, 32);
            this.Head4.setRotationPoint(0.0F, 0.0F, 0.0F);
            this.Head4.addBox(-3.5F, 0.8F, 1.0F, 1, 1, 1, 0.0F);
            this.SecondArm3 = new AdvancedModelRenderer(this, 50, 20);
            this.SecondArm3.setRotationPoint(0.0F, 0.0F, -8.0F);
            this.SecondArm3.addBox(-1.0F, 0.0F, -6.0F, 2, 1, 6, 0.0F);
            this.ThirdArm2 = new AdvancedModelRenderer(this, 50, 10);
            this.ThirdArm2.setRotationPoint(0.0F, 1.0F, 6.0F);
            this.ThirdArm2.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 8, 0.0F);
            this.EighthArm2 = new AdvancedModelRenderer(this, 80, 10);
            this.EighthArm2.setRotationPoint(5.0F, 1.0F, 0.0F);
            this.EighthArm2.addBox(0.0F, -1.0F, -1.0F, 8, 2, 2, 0.0F);
            this.FirstArm2 = new AdvancedModelRenderer(this, 50, 10);
            this.FirstArm2.setRotationPoint(0.0F, 1.0F, -6.0F);
            this.FirstArm2.addBox(-1.0F, -1.0F, -8.0F, 2, 2, 8, 0.0F);
            this.EighthArm3 = new AdvancedModelRenderer(this, 80, 20);
            this.EighthArm3.setRotationPoint(8.0F, 0.0F, 0.0F);
            this.EighthArm3.addBox(0.0F, 0.0F, -1.0F, 6, 1, 2, 0.0F);
            this.FirstArm1 = new AdvancedModelRenderer(this, 50, 0);
            this.FirstArm1.setRotationPoint(-1.2F, 22.0F, -2.0F);
            this.FirstArm1.addBox(-1.5F, -1.0F, -6.0F, 3, 3, 6, 0.0F);
            this.setRotateAngle(FirstArm1, 0.0F, 0.39269908169872414F, 0.0F);
            this.RightHorn = new AdvancedModelRenderer(this, 0, 14);
            this.RightHorn.setRotationPoint(-2.0F, -2.0F, 0.0F);
            this.RightHorn.addBox(-0.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
            this.setRotateAngle(RightHorn, 0.5462880558742251F, 0.4553564018453205F, 0.0F);
            this.FourthArm2 = new AdvancedModelRenderer(this, 50, 10);
            this.FourthArm2.setRotationPoint(0.0F, 1.0F, 6.0F);
            this.FourthArm2.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 8, 0.0F);
            this.SeventhArm2 = new AdvancedModelRenderer(this, 80, 10);
            this.SeventhArm2.setRotationPoint(5.0F, 1.0F, 0.0F);
            this.SeventhArm2.addBox(0.0F, -1.0F, -1.0F, 8, 2, 2, 0.0F);
            this.Head5 = new AdvancedModelRenderer(this, 0, 32);
            this.Head5.mirror = true;
            this.Head5.setRotationPoint(0.0F, 0.0F, 0.0F);
            this.Head5.addBox(2.5F, 0.8F, 1.0F, 1, 1, 1, 0.0F);
            this.ThirdArmDetail3 = new AdvancedModelRenderer(this, 0, 8);
            this.ThirdArmDetail3.setRotationPoint(0.0F, 1.0F, 6.0F);
            this.ThirdArmDetail3.addBox(-1.0F, 0.0F, 0.0F, 2, 0, 1, 0.0F);
            this.ThirdArmDetail2 = new AdvancedModelRenderer(this, -3, 0);
            this.ThirdArmDetail2.setRotationPoint(-1.0F, 1.0F, 1.0F);
            this.ThirdArmDetail2.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.FourthArmDetail1 = new AdvancedModelRenderer(this, -3, 0);
            this.FourthArmDetail1.setRotationPoint(1.0F, 1.0F, 1.0F);
            this.FourthArmDetail1.addBox(0.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.LeftEye = new AdvancedModelRenderer(this, 23, 44);
            this.LeftEye.setRotationPoint(0.0F, 0.0F, 0.5F);
            this.LeftEye.addBox(1.5F, -2.2F, -1.0F, 2, 2, 2, 0.0F);
            this.setRotateAngle(LeftEye, 0.0F, 0.27314402793711257F, 0.0F);
            this.FifthArm3 = new AdvancedModelRenderer(this, 80, 20);
            this.FifthArm3.setRotationPoint(-8.0F, 0.0F, 0.0F);
            this.FifthArm3.addBox(-6.0F, 0.0F, -1.0F, 6, 1, 2, 0.0F);
            this.EighthArmDetail1 = new AdvancedModelRenderer(this, 16, 3);
            this.EighthArmDetail1.setRotationPoint(0.0F, 1.0F, -1.0F);
            this.EighthArmDetail1.addBox(0.0F, 0.0F, -1.0F, 6, 0, 1, 0.0F);
            this.FourthArmDetail3 = new AdvancedModelRenderer(this, 0, 8);
            this.FourthArmDetail3.setRotationPoint(0.0F, 1.0F, 6.0F);
            this.FourthArmDetail3.addBox(-1.0F, 0.0F, 0.0F, 2, 0, 1, 0.0F);
            this.SixthArm1 = new AdvancedModelRenderer(this, 80, 0);
            this.SixthArm1.setRotationPoint(-2.4F, 22.0F, 1.2F);
            this.SixthArm1.addBox(-6.0F, -1.0F, -1.5F, 6, 3, 3, 0.0F);
            this.setRotateAngle(SixthArm1, 0.0F, 0.39269908169872414F, 0.0F);
            this.FirstArmDetail2 = new AdvancedModelRenderer(this, -6, 0);
            this.FirstArmDetail2.setRotationPoint(-1.0F, 1.0F, -5.0F);
            this.FirstArmDetail2.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.Head2 = new AdvancedModelRenderer(this, 0, 36);
            this.Head2.setRotationPoint(0.0F, 0.0F, 0.0F);
            this.Head2.addBox(-2.0F, -1.2F, -3.0F, 4, 3, 5, 0.0F);
            this.setRotateAngle(Head2, 0.7330382858376184F, -0.0F, 0.0F);
            this.SixthArm2 = new AdvancedModelRenderer(this, 80, 10);
            this.SixthArm2.setRotationPoint(-6.0F, 1.0F, 0.0F);
            this.SixthArm2.addBox(-8.0F, -1.0F, -1.0F, 8, 2, 2, 0.0F);
            this.SecondArmDetail2 = new AdvancedModelRenderer(this, -6, 0);
            this.SecondArmDetail2.setRotationPoint(-1.0F, 1.0F, -5.0F);
            this.SecondArmDetail2.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.FourthArm3 = new AdvancedModelRenderer(this, 50, 20);
            this.FourthArm3.setRotationPoint(0.0F, 0.0F, 8.0F);
            this.FourthArm3.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 6, 0.0F);
            this.Head3 = new AdvancedModelRenderer(this, 0, 44);
            this.Head3.setRotationPoint(0.0F, 0.1F, 0.9F);
            this.Head3.addBox(-2.5F, -1.6F, 6.5F, 5, 4, 1, 0.0F);
            this.SixthArmDetail3 = new AdvancedModelRenderer(this, 7, 3);
            this.SixthArmDetail3.setRotationPoint(-6.0F, 1.0F, 0.0F);
            this.SixthArmDetail3.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 2, 0.0F);
            this.ThirdArm1 = new AdvancedModelRenderer(this, 50, 0);
            this.ThirdArm1.setRotationPoint(-1.2F, 22.0F, 2.0F);
            this.ThirdArm1.addBox(-1.5F, -1.0F, 0.0F, 3, 3, 6, 0.0F);
            this.setRotateAngle(ThirdArm1, 0.0F, -0.39269908169872414F, 0.0F);
            this.FirstArmDetail3 = new AdvancedModelRenderer(this, 0, 8);
            this.FirstArmDetail3.setRotationPoint(0.0F, 1.0F, -6.0F);
            this.FirstArmDetail3.addBox(-1.0F, 0.0F, -1.0F, 2, 0, 1, 0.0F);
            this.FifthArmDetail1 = new AdvancedModelRenderer(this, 7, 0);
            this.FifthArmDetail1.setRotationPoint(0.0F, 1.0F, -1.0F);
            this.FifthArmDetail1.addBox(-6.0F, 0.0F, -1.0F, 6, 0, 1, 0.0F);
            this.SixthArmDetail2 = new AdvancedModelRenderer(this, 7, 0);
            this.SixthArmDetail2.setRotationPoint(0.0F, 1.0F, 1.0F);
            this.SixthArmDetail2.addBox(-6.0F, 0.0F, 0.0F, 6, 0, 1, 0.0F);
            this.SeventhArm1 = new AdvancedModelRenderer(this, 80, 0);
            this.SeventhArm1.setRotationPoint(3.5F, 22.0F, -1.2F);
            this.SeventhArm1.addBox(-1.0F, -1.0F, -1.5F, 6, 3, 3, 0.0F);
            this.setRotateAngle(SeventhArm1, 0.0F, 0.39269908169872414F, 0.0F);
            this.EighthArmDetail3 = new AdvancedModelRenderer(this, 7, 3);
            this.EighthArmDetail3.setRotationPoint(6.0F, 1.0F, 0.0F);
            this.EighthArmDetail3.addBox(0.0F, 0.0F, -1.0F, 1, 0, 2, 0.0F);
            this.SeventhArm3 = new AdvancedModelRenderer(this, 80, 20);
            this.SeventhArm3.setRotationPoint(8.0F, 0.0F, 0.0F);
            this.SeventhArm3.addBox(0.0F, 0.0F, -1.0F, 6, 1, 2, 0.0F);
            this.ThirdArm3 = new AdvancedModelRenderer(this, 50, 20);
            this.ThirdArm3.setRotationPoint(0.0F, 0.0F, 8.0F);
            this.ThirdArm3.addBox(-1.0F, 0.0F, 0.0F, 2, 1, 6, 0.0F);
            this.SecondArmDetail3 = new AdvancedModelRenderer(this, 0, 8);
            this.SecondArmDetail3.setRotationPoint(0.0F, 1.0F, -6.0F);
            this.SecondArmDetail3.addBox(-1.0F, 0.0F, -1.0F, 2, 0, 1, 0.0F);
            this.FourthArm1 = new AdvancedModelRenderer(this, 50, 0);
            this.FourthArm1.setRotationPoint(1.2F, 22.0F, 2.0F);
            this.FourthArm1.addBox(-1.5F, -1.0F, 0.0F, 3, 3, 6, 0.0F);
            this.setRotateAngle(FourthArm1, 0.0F, 0.39269908169872414F, 0.0F);
            this.SecondArm1 = new AdvancedModelRenderer(this, 50, 0);
            this.SecondArm1.setRotationPoint(1.2F, 22.0F, -2.0F);
            this.SecondArm1.addBox(-1.5F, -1.0F, -6.0F, 3, 3, 6, 0.0F);
            this.setRotateAngle(SecondArm1, 0.0F, -0.39269908169872414F, 0.0F);
            this.FifthArmDetail2 = new AdvancedModelRenderer(this, 7, 0);
            this.FifthArmDetail2.setRotationPoint(0.0F, 1.0F, 1.0F);
            this.FifthArmDetail2.addBox(-6.0F, 0.0F, 0.0F, 6, 0, 1, 0.0F);
            this.RightEye = new AdvancedModelRenderer(this, 14, 44);
            this.RightEye.setRotationPoint(0.0F, 0.0F, 0.5F);
            this.RightEye.addBox(-3.5F, -2.2F, -1.0F, 2, 2, 2, 0.0F);
            this.setRotateAngle(RightEye, 0.0F, -0.27314402793711257F, 0.0F);
            this.SixthArm3 = new AdvancedModelRenderer(this, 80, 20);
            this.SixthArm3.setRotationPoint(-8.0F, 0.0F, 0.0F);
            this.SixthArm3.addBox(-6.0F, 0.0F, -1.0F, 6, 1, 2, 0.0F);
            this.LeftHorn = new AdvancedModelRenderer(this, 0, 14);
            this.LeftHorn.setRotationPoint(2.3F, -2.0F, 0.0F);
            this.LeftHorn.addBox(-0.5F, -1.5F, -1.0F, 1, 2, 1, 0.0F);
            this.setRotateAngle(LeftHorn, 0.5462880558742251F, -0.4553564018453205F, 0.0F);
            this.Body = new AdvancedModelRenderer(this, 28, 53);
            this.Body.setRotationPoint(0.0F, 19.5F, 0.0F);
            this.Body.addBox(-3.5F, 1.0F, -3.5F, 7, 3, 7, 0.0F);
            this.Head1 = new AdvancedModelRenderer(this, 0, 50);
            this.Head1.setRotationPoint(0.0F, 0.6F, 1.3F);
            this.Head1.addBox(-3.0F, -2.0F, -0.5F, 6, 5, 8, 0.0F);
            this.setRotateAngle(Head1, -0.4553564018453205F, -0.0F, 0.0F);
            this.SeventhArmDetail1 = new AdvancedModelRenderer(this, 16, 3);
            this.SeventhArmDetail1.setRotationPoint(0.0F, 1.0F, -1.0F);
            this.SeventhArmDetail1.addBox(0.0F, 0.0F, -1.0F, 6, 0, 1, 0.0F);
            this.EighthArm1 = new AdvancedModelRenderer(this, 80, 0);
            this.EighthArm1.setRotationPoint(3.5F, 22.0F, 1.2F);
            this.EighthArm1.addBox(-1.0F, -1.0F, -1.5F, 6, 3, 3, 0.0F);
            this.setRotateAngle(EighthArm1, 0.0F, -0.39269908169872414F, 0.0F);
            this.SeventhArmDetail3 = new AdvancedModelRenderer(this, 7, 3);
            this.SeventhArmDetail3.setRotationPoint(6.0F, 1.0F, 0.0F);
            this.SeventhArmDetail3.addBox(0.0F, 0.0F, -1.0F, 1, 0, 2, 0.0F);
            this.FirstArm3 = new AdvancedModelRenderer(this, 50, 20);
            this.FirstArm3.setRotationPoint(0.0F, 0.0F, -8.0F);
            this.FirstArm3.addBox(-1.0F, 0.0F, -6.0F, 2, 1, 6, 0.0F);
            this.EighthArmDetail2 = new AdvancedModelRenderer(this, 16, 3);
            this.EighthArmDetail2.setRotationPoint(0.0F, 1.0F, 1.0F);
            this.EighthArmDetail2.addBox(0.0F, 0.0F, 0.0F, 6, 0, 1, 0.0F);
            this.FifthArmDetail3 = new AdvancedModelRenderer(this, 7, 3);
            this.FifthArmDetail3.setRotationPoint(-6.0F, 1.0F, 0.0F);
            this.FifthArmDetail3.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 2, 0.0F);
            this.FourthArmDetail2 = new AdvancedModelRenderer(this, -3, 0);
            this.FourthArmDetail2.setRotationPoint(-1.0F, 1.0F, 1.0F);
            this.FourthArmDetail2.addBox(-1.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.SixthArmDetail1 = new AdvancedModelRenderer(this, 7, 0);
            this.SixthArmDetail1.setRotationPoint(0.0F, 1.0F, -1.0F);
            this.SixthArmDetail1.addBox(-6.0F, 0.0F, -1.0F, 6, 0, 1, 0.0F);
            this.SecondArmDetail1 = new AdvancedModelRenderer(this, -6, 0);
            this.SecondArmDetail1.setRotationPoint(1.0F, 1.0F, -5.0F);
            this.SecondArmDetail1.addBox(0.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.FifthArm2 = new AdvancedModelRenderer(this, 80, 10);
            this.FifthArm2.setRotationPoint(-6.0F, 1.0F, -0.0F);
            this.FifthArm2.addBox(-8.0F, -1.0F, -1.0F, 8, 2, 2, 0.0F);
            this.SeventhArmDetail2 = new AdvancedModelRenderer(this, 16, 3);
            this.SeventhArmDetail2.setRotationPoint(0.0F, 1.0F, 1.0F);
            this.SeventhArmDetail2.addBox(0.0F, 0.0F, 0.0F, 6, 0, 1, 0.0F);
            this.SecondArm2 = new AdvancedModelRenderer(this, 50, 10);
            this.SecondArm2.setRotationPoint(0.0F, 1.0F, -6.0F);
            this.SecondArm2.addBox(-1.0F, -1.0F, -8.0F, 2, 2, 8, 0.0F);
            this.FirstArmDetail1 = new AdvancedModelRenderer(this, -6, 0);
            this.FirstArmDetail1.setRotationPoint(1.0F, 1.0F, -5.0F);
            this.FirstArmDetail1.addBox(0.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.ThirdArmDetail1 = new AdvancedModelRenderer(this, -3, 0);
            this.ThirdArmDetail1.setRotationPoint(1.0F, 1.0F, 1.0F);
            this.ThirdArmDetail1.addBox(0.0F, 0.0F, -1.0F, 1, 0, 6, 0.0F);
            this.FifthArm1 = new AdvancedModelRenderer(this, 80, 0);
            this.FifthArm1.setRotationPoint(-2.4F, 22.0F, -1.2F);
            this.FifthArm1.addBox(-6.0F, -1.0F, -1.5F, 6, 3, 3, 0.0F);
            this.setRotateAngle(FifthArm1, 0.0F, -0.39269908169872414F, 0.0F);
            this.Head1.addChild(this.Head4);
            this.SecondArm2.addChild(this.SecondArm3);
            this.ThirdArm1.addChild(this.ThirdArm2);
            this.EighthArm1.addChild(this.EighthArm2);
            this.FirstArm1.addChild(this.FirstArm2);
            this.EighthArm2.addChild(this.EighthArm3);
            this.RightEye.addChild(this.RightHorn);
            this.FourthArm1.addChild(this.FourthArm2);
            this.SeventhArm1.addChild(this.SeventhArm2);
            this.Head1.addChild(this.Head5);
            this.ThirdArm3.addChild(this.ThirdArmDetail3);
            this.ThirdArm3.addChild(this.ThirdArmDetail2);
            this.FourthArm3.addChild(this.FourthArmDetail1);
            this.Head1.addChild(this.LeftEye);
            this.FifthArm2.addChild(this.FifthArm3);
            this.EighthArm3.addChild(this.EighthArmDetail1);
            this.FourthArm3.addChild(this.FourthArmDetail3);
            this.FirstArm3.addChild(this.FirstArmDetail2);
            this.Body.addChild(this.Head2);
            this.SixthArm1.addChild(this.SixthArm2);
            this.SecondArm3.addChild(this.SecondArmDetail2);
            this.FourthArm2.addChild(this.FourthArm3);
            this.Head1.addChild(this.Head3);
            this.SixthArm3.addChild(this.SixthArmDetail3);
            this.FirstArm3.addChild(this.FirstArmDetail3);
            this.FifthArm3.addChild(this.FifthArmDetail1);
            this.SixthArm3.addChild(this.SixthArmDetail2);
            this.EighthArm3.addChild(this.EighthArmDetail3);
            this.SeventhArm2.addChild(this.SeventhArm3);
            this.ThirdArm2.addChild(this.ThirdArm3);
            this.SecondArm3.addChild(this.SecondArmDetail3);
            this.FifthArm3.addChild(this.FifthArmDetail2);
            this.Head1.addChild(this.RightEye);
            this.SixthArm2.addChild(this.SixthArm3);
            this.LeftEye.addChild(this.LeftHorn);
            this.Head2.addChild(this.Head1);
            this.SeventhArm3.addChild(this.SeventhArmDetail1);
            this.SeventhArm3.addChild(this.SeventhArmDetail3);
            this.FirstArm2.addChild(this.FirstArm3);
            this.EighthArm3.addChild(this.EighthArmDetail2);
            this.FifthArm3.addChild(this.FifthArmDetail3);
            this.FourthArm3.addChild(this.FourthArmDetail2);
            this.SixthArm3.addChild(this.SixthArmDetail1);
            this.SecondArm3.addChild(this.SecondArmDetail1);
            this.FifthArm1.addChild(this.FifthArm2);
            this.SeventhArm3.addChild(this.SeventhArmDetail2);
            this.SecondArm1.addChild(this.SecondArm2);
            this.FirstArm3.addChild(this.FirstArmDetail1);
            this.ThirdArm3.addChild(this.ThirdArmDetail1);
            this.animator = ModelAnimator.create();
        }

        @Override
        public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
            this.FirstArm1.render(f5);
            this.SixthArm1.render(f5);
            this.ThirdArm1.render(f5);
            this.SeventhArm1.render(f5);
            this.FourthArm1.render(f5);
            this.SecondArm1.render(f5);
            this.Body.render(f5);
            this.EighthArm1.render(f5);
            this.FifthArm1.render(f5);
        }

        /**
         * This is a helper function from Tabula to set the rotation of model parts
         */
        public void setRotateAngle(AdvancedModelRenderer modelRenderer, float x, float y, float z) {
            modelRenderer.rotateAngleX = x;
            modelRenderer.rotateAngleY = y;
            modelRenderer.rotateAngleZ = z;
        }
    }

